# Generated by Django 3.1.7 on 2021-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=250),
        ),
    ]
